/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Content {
  'id' : string,
  'url' : string,
  'title' : string,
  'contentText' : string,
  'metadata' : string,
  'description' : string,
  'platform' : Platform,
}
export interface CreatorProfile {
  'contentPillars' : Array<string>,
  'about' : string,
  'blogUrl' : [] | [string],
  'voiceCharacteristics' : string,
  'podcastUrl' : [] | [string],
  'twitterUrl' : [] | [string],
  'instagramUrl' : [] | [string],
  'newsletterUrl' : [] | [string],
  'brandColors' : Array<string>,
  'brandName' : string,
  'youtubeUrl' : [] | [string],
  'tiktokUrl' : [] | [string],
}
export type InsightCategory = { 'contentPerformance' : null } |
  { 'strategicLearning' : null } |
  { 'audiencePreference' : null } |
  { 'messagingPattern' : null } |
  { 'brandVoiceSignal' : null };
export type Platform = { 'tiktok' : null } |
  { 'twitter' : null } |
  { 'blog' : null } |
  { 'instagram' : null } |
  { 'podcast' : null } |
  { 'youtube' : null } |
  { 'newsletter' : null };
export interface ProfileInsight {
  'insightText' : string,
  'sourceLink' : string,
  'timestamp' : bigint,
  'category' : InsightCategory,
}
export interface _SERVICE {
  'addContent' : ActorMethod<
    [string, Platform, string, string, string, string],
    string
  >,
  'addProfileInsight' : ActorMethod<[ProfileInsight], undefined>,
  'createProfile' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      Array<string>,
      string,
      Array<string>,
      string,
    ],
    undefined
  >,
  'getAllContent' : ActorMethod<[], Array<Content>>,
  'getContent' : ActorMethod<[string], Content>,
  'getProfileInsights' : ActorMethod<[], Array<ProfileInsight>>,
  'getProfiles' : ActorMethod<[], Array<CreatorProfile>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];