/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Platform = IDL.Variant({
  'tiktok' : IDL.Null,
  'twitter' : IDL.Null,
  'blog' : IDL.Null,
  'instagram' : IDL.Null,
  'podcast' : IDL.Null,
  'youtube' : IDL.Null,
  'newsletter' : IDL.Null,
});
export const InsightCategory = IDL.Variant({
  'contentPerformance' : IDL.Null,
  'strategicLearning' : IDL.Null,
  'audiencePreference' : IDL.Null,
  'messagingPattern' : IDL.Null,
  'brandVoiceSignal' : IDL.Null,
});
export const ProfileInsight = IDL.Record({
  'insightText' : IDL.Text,
  'sourceLink' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : InsightCategory,
});
export const Content = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'contentText' : IDL.Text,
  'metadata' : IDL.Text,
  'description' : IDL.Text,
  'platform' : Platform,
});
export const CreatorProfile = IDL.Record({
  'contentPillars' : IDL.Vec(IDL.Text),
  'about' : IDL.Text,
  'blogUrl' : IDL.Opt(IDL.Text),
  'voiceCharacteristics' : IDL.Text,
  'podcastUrl' : IDL.Opt(IDL.Text),
  'twitterUrl' : IDL.Opt(IDL.Text),
  'instagramUrl' : IDL.Opt(IDL.Text),
  'newsletterUrl' : IDL.Opt(IDL.Text),
  'brandColors' : IDL.Vec(IDL.Text),
  'brandName' : IDL.Text,
  'youtubeUrl' : IDL.Opt(IDL.Text),
  'tiktokUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addContent' : IDL.Func(
      [IDL.Text, Platform, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addProfileInsight' : IDL.Func([ProfileInsight], [], []),
  'createProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'getAllContent' : IDL.Func([], [IDL.Vec(Content)], ['query']),
  'getContent' : IDL.Func([IDL.Text], [Content], ['query']),
  'getProfileInsights' : IDL.Func([], [IDL.Vec(ProfileInsight)], ['query']),
  'getProfiles' : IDL.Func([], [IDL.Vec(CreatorProfile)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Platform = IDL.Variant({
    'tiktok' : IDL.Null,
    'twitter' : IDL.Null,
    'blog' : IDL.Null,
    'instagram' : IDL.Null,
    'podcast' : IDL.Null,
    'youtube' : IDL.Null,
    'newsletter' : IDL.Null,
  });
  const InsightCategory = IDL.Variant({
    'contentPerformance' : IDL.Null,
    'strategicLearning' : IDL.Null,
    'audiencePreference' : IDL.Null,
    'messagingPattern' : IDL.Null,
    'brandVoiceSignal' : IDL.Null,
  });
  const ProfileInsight = IDL.Record({
    'insightText' : IDL.Text,
    'sourceLink' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : InsightCategory,
  });
  const Content = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'contentText' : IDL.Text,
    'metadata' : IDL.Text,
    'description' : IDL.Text,
    'platform' : Platform,
  });
  const CreatorProfile = IDL.Record({
    'contentPillars' : IDL.Vec(IDL.Text),
    'about' : IDL.Text,
    'blogUrl' : IDL.Opt(IDL.Text),
    'voiceCharacteristics' : IDL.Text,
    'podcastUrl' : IDL.Opt(IDL.Text),
    'twitterUrl' : IDL.Opt(IDL.Text),
    'instagramUrl' : IDL.Opt(IDL.Text),
    'newsletterUrl' : IDL.Opt(IDL.Text),
    'brandColors' : IDL.Vec(IDL.Text),
    'brandName' : IDL.Text,
    'youtubeUrl' : IDL.Opt(IDL.Text),
    'tiktokUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addContent' : IDL.Func(
        [IDL.Text, Platform, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addProfileInsight' : IDL.Func([ProfileInsight], [], []),
    'createProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'getAllContent' : IDL.Func([], [IDL.Vec(Content)], ['query']),
    'getContent' : IDL.Func([IDL.Text], [Content], ['query']),
    'getProfileInsights' : IDL.Func([], [IDL.Vec(ProfileInsight)], ['query']),
    'getProfiles' : IDL.Func([], [IDL.Vec(CreatorProfile)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };