/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProfileInsight {
    insightText: string;
    sourceLink: string;
    timestamp: bigint;
    category: InsightCategory;
}
export interface CreatorProfile {
    contentPillars: Array<string>;
    about: string;
    blogUrl?: string;
    voiceCharacteristics: string;
    podcastUrl?: string;
    twitterUrl?: string;
    instagramUrl?: string;
    newsletterUrl?: string;
    brandColors: Array<string>;
    brandName: string;
    youtubeUrl?: string;
    tiktokUrl?: string;
}
export interface Content {
    id: string;
    url: string;
    title: string;
    contentText: string;
    metadata: string;
    description: string;
    platform: Platform;
}
export enum InsightCategory {
    contentPerformance = "contentPerformance",
    strategicLearning = "strategicLearning",
    audiencePreference = "audiencePreference",
    messagingPattern = "messagingPattern",
    brandVoiceSignal = "brandVoiceSignal"
}
export enum Platform {
    tiktok = "tiktok",
    twitter = "twitter",
    blog = "blog",
    instagram = "instagram",
    podcast = "podcast",
    youtube = "youtube",
    newsletter = "newsletter"
}
export interface backendInterface {
    addContent(url: string, platform: Platform, title: string, description: string, contentText: string, metadata: string): Promise<string>;
    addProfileInsight(insight: ProfileInsight): Promise<void>;
    createProfile(brandName: string, instagramUrl: string | null, tiktokUrl: string | null, youtubeUrl: string | null, twitterUrl: string | null, newsletterUrl: string | null, blogUrl: string | null, podcastUrl: string | null, brandColors: Array<string>, voiceCharacteristics: string, contentPillars: Array<string>, about: string): Promise<void>;
    getAllContent(): Promise<Array<Content>>;
    getContent(id: string): Promise<Content>;
    getProfileInsights(): Promise<Array<ProfileInsight>>;
    getProfiles(): Promise<Array<CreatorProfile>>;
}
import type { Content as _Content, CreatorProfile as _CreatorProfile, InsightCategory as _InsightCategory, Platform as _Platform, ProfileInsight as _ProfileInsight } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContent(arg0: string, arg1: Platform, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addContent(arg0, to_candid_Platform_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContent(arg0, to_candid_Platform_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addProfileInsight(arg0: ProfileInsight): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProfileInsight(to_candid_ProfileInsight_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProfileInsight(to_candid_ProfileInsight_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string | null, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: Array<string>, arg9: string, arg10: Array<string>, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async getAllContent(): Promise<Array<Content>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContent();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContent();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContent(arg0: string): Promise<Content> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent(arg0);
                return from_candid_Content_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent(arg0);
            return from_candid_Content_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileInsights(): Promise<Array<ProfileInsight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileInsights();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileInsights();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfiles(): Promise<Array<CreatorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfiles();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfiles();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Content_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Content): Content {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CreatorProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreatorProfile): CreatorProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InsightCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InsightCategory): InsightCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Platform_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Platform): Platform {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileInsight_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileInsight): ProfileInsight {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    url: string;
    title: string;
    contentText: string;
    metadata: string;
    description: string;
    platform: _Platform;
}): {
    id: string;
    url: string;
    title: string;
    contentText: string;
    metadata: string;
    description: string;
    platform: Platform;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        contentText: value.contentText,
        metadata: value.metadata,
        description: value.description,
        platform: from_candid_Platform_n11(_uploadFile, _downloadFile, value.platform)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insightText: string;
    sourceLink: string;
    timestamp: bigint;
    category: _InsightCategory;
}): {
    insightText: string;
    sourceLink: string;
    timestamp: bigint;
    category: InsightCategory;
} {
    return {
        insightText: value.insightText,
        sourceLink: value.sourceLink,
        timestamp: value.timestamp,
        category: from_candid_InsightCategory_n16(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentPillars: Array<string>;
    about: string;
    blogUrl: [] | [string];
    voiceCharacteristics: string;
    podcastUrl: [] | [string];
    twitterUrl: [] | [string];
    instagramUrl: [] | [string];
    newsletterUrl: [] | [string];
    brandColors: Array<string>;
    brandName: string;
    youtubeUrl: [] | [string];
    tiktokUrl: [] | [string];
}): {
    contentPillars: Array<string>;
    about: string;
    blogUrl?: string;
    voiceCharacteristics: string;
    podcastUrl?: string;
    twitterUrl?: string;
    instagramUrl?: string;
    newsletterUrl?: string;
    brandColors: Array<string>;
    brandName: string;
    youtubeUrl?: string;
    tiktokUrl?: string;
} {
    return {
        contentPillars: value.contentPillars,
        about: value.about,
        blogUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.blogUrl)),
        voiceCharacteristics: value.voiceCharacteristics,
        podcastUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.podcastUrl)),
        twitterUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.twitterUrl)),
        instagramUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.instagramUrl)),
        newsletterUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.newsletterUrl)),
        brandColors: value.brandColors,
        brandName: value.brandName,
        youtubeUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.youtubeUrl)),
        tiktokUrl: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.tiktokUrl))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiktok: null;
} | {
    twitter: null;
} | {
    blog: null;
} | {
    instagram: null;
} | {
    podcast: null;
} | {
    youtube: null;
} | {
    newsletter: null;
}): Platform {
    return "tiktok" in value ? Platform.tiktok : "twitter" in value ? Platform.twitter : "blog" in value ? Platform.blog : "instagram" in value ? Platform.instagram : "podcast" in value ? Platform.podcast : "youtube" in value ? Platform.youtube : "newsletter" in value ? Platform.newsletter : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contentPerformance: null;
} | {
    strategicLearning: null;
} | {
    audiencePreference: null;
} | {
    messagingPattern: null;
} | {
    brandVoiceSignal: null;
}): InsightCategory {
    return "contentPerformance" in value ? InsightCategory.contentPerformance : "strategicLearning" in value ? InsightCategory.strategicLearning : "audiencePreference" in value ? InsightCategory.audiencePreference : "messagingPattern" in value ? InsightCategory.messagingPattern : "brandVoiceSignal" in value ? InsightCategory.brandVoiceSignal : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfileInsight>): Array<ProfileInsight> {
    return value.map((x)=>from_candid_ProfileInsight_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CreatorProfile>): Array<CreatorProfile> {
    return value.map((x)=>from_candid_CreatorProfile_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Content>): Array<Content> {
    return value.map((x)=>from_candid_Content_n9(_uploadFile, _downloadFile, x));
}
function to_candid_InsightCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsightCategory): _InsightCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Platform_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): _Platform {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileInsight_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileInsight): _ProfileInsight {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insightText: string;
    sourceLink: string;
    timestamp: bigint;
    category: InsightCategory;
}): {
    insightText: string;
    sourceLink: string;
    timestamp: bigint;
    category: _InsightCategory;
} {
    return {
        insightText: value.insightText,
        sourceLink: value.sourceLink,
        timestamp: value.timestamp,
        category: to_candid_InsightCategory_n5(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Platform): {
    tiktok: null;
} | {
    twitter: null;
} | {
    blog: null;
} | {
    instagram: null;
} | {
    podcast: null;
} | {
    youtube: null;
} | {
    newsletter: null;
} {
    return value == Platform.tiktok ? {
        tiktok: null
    } : value == Platform.twitter ? {
        twitter: null
    } : value == Platform.blog ? {
        blog: null
    } : value == Platform.instagram ? {
        instagram: null
    } : value == Platform.podcast ? {
        podcast: null
    } : value == Platform.youtube ? {
        youtube: null
    } : value == Platform.newsletter ? {
        newsletter: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InsightCategory): {
    contentPerformance: null;
} | {
    strategicLearning: null;
} | {
    audiencePreference: null;
} | {
    messagingPattern: null;
} | {
    brandVoiceSignal: null;
} {
    return value == InsightCategory.contentPerformance ? {
        contentPerformance: null
    } : value == InsightCategory.strategicLearning ? {
        strategicLearning: null
    } : value == InsightCategory.audiencePreference ? {
        audiencePreference: null
    } : value == InsightCategory.messagingPattern ? {
        messagingPattern: null
    } : value == InsightCategory.brandVoiceSignal ? {
        brandVoiceSignal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
